// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF2GjriTPRa0WDn6_AUrMbAd6SvZx3p4U',
    appId: '1:113843920620:web:de7269a6ac1dce8bc94fc9',
    messagingSenderId: '113843920620',
    projectId: 'aexinl',
    authDomain: 'aexinl.firebaseapp.com',
    databaseURL: 'https://aexinl-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aexinl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUHx9R2qLWi_h9B4zzL9dKay0pl5yvv4I',
    appId: '1:113843920620:android:4bee8a7817995aeac94fc9',
    messagingSenderId: '113843920620',
    projectId: 'aexinl',
    databaseURL: 'https://aexinl-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aexinl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY7mdt_6va7Xc4j5C6MkFtoFdd_DQmiDo',
    appId: '1:113843920620:ios:9a946d14e69065e8c94fc9',
    messagingSenderId: '113843920620',
    projectId: 'aexinl',
    databaseURL: 'https://aexinl-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aexinl.appspot.com',
    iosBundleId: 'com.example.posttest5096FilipusManik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY7mdt_6va7Xc4j5C6MkFtoFdd_DQmiDo',
    appId: '1:113843920620:ios:f08dbebcf645ebbdc94fc9',
    messagingSenderId: '113843920620',
    projectId: 'aexinl',
    databaseURL: 'https://aexinl-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aexinl.appspot.com',
    iosBundleId: 'com.example.posttest5096FilipusManik.RunnerTests',
  );
}
