// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrhkPnFlvSH5vOUTISa7YrEyW401b_Ceo',
    appId: '1:748015536984:web:bad871aac257ac2cd2b32d',
    messagingSenderId: '748015536984',
    projectId: 'pertemuan-9-mobile-701ff',
    authDomain: 'pertemuan-9-mobile-701ff.firebaseapp.com',
    storageBucket: 'pertemuan-9-mobile-701ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7yIGB8PER3r7SDEh-joyEThcPixErZa0',
    appId: '1:748015536984:android:9874e2711b1b85c5d2b32d',
    messagingSenderId: '748015536984',
    projectId: 'pertemuan-9-mobile-701ff',
    storageBucket: 'pertemuan-9-mobile-701ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQS3J3OkgDpb0dsCgqeUt3n2q8D4bfnk8',
    appId: '1:748015536984:ios:29dde063eebcf3dfd2b32d',
    messagingSenderId: '748015536984',
    projectId: 'pertemuan-9-mobile-701ff',
    storageBucket: 'pertemuan-9-mobile-701ff.appspot.com',
    iosBundleId: 'com.example.pertemuan9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQS3J3OkgDpb0dsCgqeUt3n2q8D4bfnk8',
    appId: '1:748015536984:ios:52bab6b0757f59dcd2b32d',
    messagingSenderId: '748015536984',
    projectId: 'pertemuan-9-mobile-701ff',
    storageBucket: 'pertemuan-9-mobile-701ff.appspot.com',
    iosBundleId: 'com.example.pertemuan9.RunnerTests',
  );
}
